import { StyleSheet, Platform, StatusBar, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A1A40",
  },
  gradient: {
    flex: 1,
    padding: 20,
  },
  backButton: {
    position: "absolute",
    top: Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) + 20 : 20,
    left: 20,
    zIndex: 1,
  },
  content: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 24,
    color: "white",
    textAlign: "center",
    marginBottom: 15,
    marginTop: 80,
  },
  statusTitle: {
    fontSize: 24,
    color: "white",
    textAlign: "center",
    marginBottom: 15,
    marginTop: 80,
  },
  subtitle: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.8)",
    textAlign: "left",
    marginBottom: 40,
    marginTop: 20,
  },
  statusSubtitle: {
    marginBottom: 20,
    marginTop: 20,
    color: "white",
    textAlign: "center",
  },
  requirementsList: {
    width: "100%",
    marginBottom: 40,
  },
  requirementItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  requirementText: {
    color: "white",
    fontSize: 16,
    marginLeft: 12,
  },
  cameraContainer: {
    width: "100%",
    height: "70%",
    borderRadius: 20,
    overflow: "hidden",
    marginBottom: 40,
    marginTop:
      Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) + 60 : 60,
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  selfieGuide: {
    width: width * 0.67,
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  selfieOutline: {
    width: "100%",
    height: "100%",
    borderRadius: width * 0.325,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  idGuide: {
    width: width * 0.9,
    aspectRatio: 1.3,
    justifyContent: "center",
    alignItems: "center",
  },
  idOutline: {
    width: "100%",
    height: "100%",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderRadius: 8,
  },
  captureButton: {
    position: "absolute",
    bottom: 20,
    alignSelf: "center",
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  captureButtonInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "white",
  },
  submitText: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  verificationSubmitButton: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  completeContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  decorativeIcon: {
    width: 40,
    height: 40,
    position: "absolute",
    bottom: 50,
    alignSelf: "center",
  },
  stepsDecorativeIcon: {
    width: 40,
    height: 40,
    position: "absolute",
    bottom: 15,
    alignSelf: "center",
  },
  confirmDecorativeIcon: {
    width: 40,
    height: 40,
    position: "absolute",
    bottom: 30,
    alignSelf: "center",
  },
  photoGrid: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 20,
    justifyContent: "center",
    marginBottom: 75,
  },
  thumbnailImage: {
    width: width * 0.25,
    height: width * 0.25,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  forgotPasswordButton: {
    alignItems: "center",
    marginTop: 10,
    position: "absolute",
    top: 100,
  },
  stepsContainer: {
    marginVertical: 20,
    alignItems: "flex-start",
    paddingHorizontal: 20,
    marginTop: 50,
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  stepText: {
    color: "white",
    fontSize: 16,
    marginLeft: 10,
  },
  infoText: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 16,
    textAlign: "center",
    marginVertical: 20,
  },
  infoTextItem: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 14,
    textAlign: "left",
    marginHorizontal: 20,
    marginBottom: 5,
    paddingTop: 10,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  retakeButton: {
    backgroundColor: "#E74C3C",
    paddingVertical: 20,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginRight: 10,
    width: "50%",
    alignSelf: "center",
  },
  verificationSubmitContainer: {
    marginTop: 50,
  },
  submitButton: {
    backgroundColor: "#16A085",
    paddingVertical: 20,
    paddingHorizontal: 25,
    borderRadius: 25,
    width: "90%",
    alignSelf: "center",
  },
  confirmSubmitButton: {
    backgroundColor: "#16A085",
    paddingVertical: 20,
    paddingHorizontal: 25,
    borderRadius: 25,
    width: "50%",
    alignSelf: "center",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  startVerificationButton: {
    backgroundColor: "#3498DB",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 15,
    width: "40%",
  },
  infoTextContainer: {
    marginHorizontal: 10,
    marginBottom: 20,
    alignItems: "flex-start",
    marginTop: -25,
    marginLeft: -10,
  },
  whyInfoTextContainer: {
    marginHorizontal: 10,
    marginBottom: 30,
    alignItems: "flex-start",
    marginTop: -10,
    marginLeft: -1,
  },
  overlayText: {
    position: "absolute",
    bottom: -40,
    color: "black",
    fontSize: 18,
    textAlign: "center",
    fontWeight: 500,
  },
});
